### ISSUE TITLE
Streaming version

### ISSUE THREAD

**Issue by oncletom** [ngryman/reading-time#1]
Hi there,

do you mind if I propose a PR which accepts a readableStream (and possibly works with Buffers rather than string conversion)?

Thanks :-)

**Comment by ngryman** [comment]
Hey,

Good idea! That said, I'd prefer this module to stay super simple and focused.
Do you think it would be easy for you to wrap the existing implementation and add streaming support?
If so you could create a `reading-time-stream` package which depends on `reading-time`.
I would update my `readme` to point to your streaming version.

What do you think?

PS: Bordelais ? :wine_glass:

**Comment by oncletom** [comment]
Hm, I don't think it will share much of its code (yet) but I'll show what what I end up with, and we'll see.
If it has to be in a separate module, I am okay for that.

The idea would be for people to do a `require('reading-time/stream')` to keep your API simple.

PS: j'eusse été ;-)
