### ISSUE TITLE
i18n or change "min read"

### ISSUE THREAD

**Issue by polalegria** [ngryman/reading-time#17]
Hi,

Its possible translate or change text "min read"?

Thanks

**Comment by ngryman** [comment]
Hey, sorry for the late answer.

Currently you do:
```js
const stats = readingTime(text)
console.log(`$[Math.ceil(minutes.toFixed(2))} whatever you want`)
```

I could perhaps return the minutes already rounded so it's easier. Tell me if that's ok for you.

**Comment by ngryman** [comment]
> Or pipe the time to moment.js
Good idea, I should expose a bare version that returns the duration in seconds so you can process it however you like.

**Comment by ngryman** [comment]
Closing this and continuing here: https://github.com/ngryman/reading-time/issues/18
