### ISSUE TITLE
Change the API

### ISSUE THREAD

**Issue by ngryman** [ngryman/reading-time#18]
Currently `readingTime` returns an object of the form:
```js
{
  text: displayed + ' min read',
  minutes: minutes,
  time: time,
  words: words
}
```

That's too much and it's not easily composable. Let's decouple things and expose this API:
```js
export const countWords = (text: string, options?: { bound?: string => boolean }): number
export const readingTime = (wordCount: number, options?: { wordsPerMinute?: number }): number
export default function(text, options) {
  return readingTime(countWords(text, options), options)
}
```

**Comment by Xapphire13** [comment]
This looks good to me! Will `readingTime()` return in minutes or ms with this API?

**Comment by ngryman** [comment]
I think that seconds would be the best time resolution as reading times generally vary from under 1 minute to several minutes. It's easily convertible to `ms` (if you really need it) or to `minutes`.

**Comment by Xapphire13** [comment]
Sounds good!

**Comment by ngryman** [comment]
Got it. I agree that the `text` field is not very useful, I think we should get rid of it. For the rest let's keep it that way for now.

So the new result would just be:
```ts
type Result = {
  minutes: minutes,
  time: time,
  words: words
}
```

I still kind of like the idea of decoupling word counting from reading time computation in case users want to customize things. It's pretty cheap to achieve so why not 🤷 

I think we can do that while not breaking the current API:

```ts
type countWords = (text: string, options?: { bound?: string => boolean }): number

type readingTimeWith = (wordCount: number, options?: { wordsPerMinute?: number }): Result
type readingTime = (text: string, options?: { wordsPerMinute?: number }): Result
```

@Josh-Cena What do you think?

**Comment by Josh-Cena** [comment]
LGTM, we should allow people to control this process more granularly, while one single convenient API would still be good for normal users👍

**Comment by Josh-Cena** [comment]
Another thing I noticed when I'm refactoring the test suite: the `minutes` field is not tested at all, and it's trivially `time / 60000`. Moreover, in the `stream` version, floating point errors build up when adding the `minutes` together, so the final minutes stat can deviate a lot. I think we should export only `time` (exact time in milliseconds) and `displayed` (rounded minutes stats), and let the user convert it to other measures if they need.
