### ISSUE TITLE
question on API

### ISSUE THREAD

**Issue by johnpapa** [ngryman/reading-time#26]
I'm considering making a VS Code extension using this library ... is this being actively updated?

Will the API be modified as per this issue? #18 

Also, I noticed that the typescript typings file does not include the `options` argument.

Or do you recommend I fork this?

**Comment by johnpapa** [comment]
Please notice the PR #27 

If you would consider this and publish to npm, I would appreciate it. If this is not something you wish to pull in, please let me know so I can figure out if I should fork or use another calculation.

Thanks for your time!

**Comment by ngryman** [comment]
Hey John,

Sure I think the API proposal in #18 makes sense. Are you ok to open a PR for that?
I've reviewed #27 (thanks for the changes), just a couple of minor things and let's ship it!

**Comment by johnpapa** [comment]
I think what you have is fine, but if you decide to make #18, please just move it to v2 since it is a breaking change).

I updated #27 for ya.

Thanks for considering!
