### ISSUE TITLE
v1.5.0 requires additional Webpack config

### ISSUE THREAD

**Issue by Josh-Cena** [ngryman/reading-time#44]
Just jumping in to say that, with my current setup, `v1.4.0` worked fine without any changes, but updating to `v1.5.0` required me to add the following to my webpack config:

```js
node: {
  global: true
},
resolve: {
  fallback: {
    stream: 'stream-browserify'
  }
},
plugins: [
  new webpack.ProvidePlugin({
    process: 'process/browser',
    Buffer: ['buffer', 'Buffer']
  })
]
```

and had to install `stream-browserify`.

The problematic line was `const Transform = require('stream').Transform`, but this line is also present in `v1.4.0`. This is a node core package, so it is expected for some kind of polyfill to be needed, but for some strange reason, `v1.4.0` just works without any particular configuration change. 🤷‍♂️

_Originally posted by @miguelcobain in https://github.com/ngryman/reading-time/issues/38#issuecomment-945313045_

**Comment by Josh-Cena** [comment]
Hi @miguelcobain I created a new issue for you.

I actually don't know much about your use-case. Are you trying to use `Buffer` in a browser environment? (I don't think people use Webpack for Node apps?) What was the error before you fixed your Webpack?

**Comment by miguelcobain** [comment]
Yes, I'm using `reading-time` in a browser context. It works great!

Before my webpack fixes, the error I got was basically complaining about the `stream` import (which of course doesn't exist in a browser environment).

Here is the error:

```
ERROR in ./node_modules/reading-time/lib/stream.js 7:63-90
Module not found: Error: Can't resolve 'stream' in '/Users/miguel/workspace/curtaemeia/node_modules/reading-time/lib'
Did you mean './stream'?
Requests that should resolve in the current directory need to start with './'.
Requests that start with a name are treated as module requests and resolve within module directories (node_modules).
If changing the source code is not an option there is also a resolve options called 'preferRelative' which tries to resolve these kind of requests in the current directory too.

BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
	- add a fallback 'resolve.fallback: { "stream": require.resolve("stream-browserify") }'
	- install 'stream-browserify'
If you don't want to include a polyfill, you can use an empty module like this:
	resolve.fallback: { "stream": false }
```

**Comment by miguelcobain** [comment]
Ok, here's a wild guess. I've been looking at the diff between 1.4.0 and 1.5.0 and I saw this change:

![image](https://user-images.githubusercontent.com/631691/137661732-76356468-e1dc-45b2-9ee9-2fdee55fef22.png)

Perhaps webpack wasn't even bundling the `stream` file at all before, because it wasn't referenced in the index.js file. So perhaps I didn't get an error because I'm not using the stream support in my project.

But now, the stream file is imported, which forces webpack to bundle it, and then this problem emerges.

**Comment by Josh-Cena** [comment]
And yes, I would do a quick note. Thanks for the reminder :P

**Comment by miguelcobain** [comment]
Indeed, adding `"browser": "lib/reading-time.js"` to `reading-time`'s package.json, and then using `import readingTime from 'reading-time';`, works great.

But doesn't this mean that browser users will not be able to get the stream feature at all?

**Comment by Josh-Cena** [comment]
> But doesn't this mean that browser users will not be able to get the stream feature at all?

They still can by importing from `lib/stream`, but the stream version is rarely used anyways, and with an even much smaller group who would use it in a browser context. Before 1.5.0 it wasn't even exported in the main entry point, so... let's make the majority happy

**Comment by miguelcobain** [comment]
Perhaps adding the note that you mentioned above:

> They still can by importing from lib/stream

Bonus points if we could add the necessary webpack config I posted in a spoiler like this: https://gist.github.com/jbsulli/03df3cdce94ee97937ebda0ffef28287

**Comment by Josh-Cena** [comment]
> Perhaps adding the note that you mentioned above:

I did that in a later commit, so just read the docs on the front page instead of looking at the diff.

> Bonus points if we could add the necessary webpack config I posted in a spoiler like this:

I suspect users who need to use the stream version already know about the `Buffer` polyfill, so... maybe not too much education ;)

**Comment by miguelcobain** [comment]
It's perfect!
My pleasure. Thanks for the quick turnaround and useful library.

**Comment by Char2sGu** [comment]
@Josh-Cena Surprised to see my old friend here <3
