### ISSUE TITLE
Cannot find module 'readingTime' or its corresponding type declarations.

### ISSUE THREAD

**Issue by bhatvikrant** [ngryman/reading-time#48]
My nextjs cannot find type declarations
<img width="646" alt="Screenshot 2021-11-29 at 3 14 57 PM" src="https://user-images.githubusercontent.com/50735025/143844685-016dda34-b7a8-4268-a7e1-0f97158f85ae.png">

**Comment by Josh-Cena** [comment]
Hi, this module is called `reading-time`. You need to import it as `import readingTime from 'reading-time'`.

**Comment by bhatvikrant** [comment]
Oops, thanks for pointing that out!
