### ISSUE TITLE
Reading time on one letter returns 'null'

### ISSUE THREAD

**Issue by oncletom** [ngryman/reading-time#5]
There is a weird behaviour that causes reading-time to return `null`.

```js
const t = require('reading-time');

t('OK'); // -> { time: ... }

// but
t('O'); // -> null

// whereas
t('😊'); // -> { time: ... } (certainly because it is a two bytes char)
t(''); // -> { time: ... }
```

So I am not sure why `null` is returned and if it should rather throw an exception or anything. But 'one letter' is definitely 'one word' and should consistently return an object.

An error (and not null) should rather be raised if the given input is not a string (not being able to be stringified — not sure we want to be able to try to get a result for `{ foo: 'bar' }` argument).

**Comment by ngryman** [comment]
Nice catch, `0` is definitely a word. `reading-time` should never return an error. I'll look into it. Sorry for the delay...

**Comment by oncletom** [comment]
No worries :-) I guess it's related to `if (start == end) return null;` and how you compute the `end` var.

**Comment by ngryman** [comment]
Yes it's that, I'm removing this check. It's kind of useless. It will instead return an object with stats for no words.

**Comment by ngryman** [comment]
New version has been published with the fix. Note that the `api` has changed as now it will never return `null`.

**Comment by oncletom** [comment]
Ace! Thanks a lot :-)
