### ISSUE TITLE
Math.round Minutes by default

### ISSUE THREAD

**Issue by surjithctly** [ngryman/reading-time#55]
Currently the minutes returns `5.87` or `6.43` like this. 

But nobody wanted to read like that. I checked the source and it seems the round is added, but it's not working. 

Could be a bug? 

Here's a minimal reproduction: https://stackblitz.com/edit/node-nyf9tn?file=index.js

Run `node index` to see the result.

**Comment by DerTimonius** [comment]
I'd love to take a look into this issue 🙂

**Comment by Josh-Cena** [comment]
Hi @surjithctly you are using 1.5.0. In v1, `minutes` is the raw time without any rounding. You need to use `displayed` to get the rounded behavior. In v2 (currently 2.0.0-1), we no longer have the raw `minutes`, and `minutes` is rounded by default, so you should try it out.
