### ISSUE TITLE
readingTimeWithCount() not exported

### ISSUE THREAD

**Issue by shuckster** [ngryman/reading-time#58]
Just noticed the above function is documented but not available in NPM:

- https://www.npmjs.com/package/reading-time?activeTab=code

The same appears to be true for `countWords()`.

**Comment by Josh-Cena** [comment]
Hi! `readingTimeWithCount` is a 2.0 feature. If you want to try it, you have to use `2.0.0-1` instead.

**Comment by shuckster** [comment]
Ah, I see now. Thank you!
